### ISSUE TITLE
Assertion Failures in README.md Code

### ISSUE THREAD

**Issue by tcoard** [facebookresearch/loop_tool#6]
I tried to run the code from the README.md, but some of the assertions fail.

Asserts that fail:
* `assert np.allclose(W.numpy(), np.sum(X.numpy() * Z.numpy()))`
* `assert np.allclose(new_W.numpy(), np.sum(new_X.numpy() * new_Z.numpy()))`

When I print the variables, the values change. So could be related to that. I set `np.random.seed(0)` but that didn't help.

Running:
```
print(f"{W.numpy()=}, {np.sum(X.numpy() * Z.numpy())=}")
print(f"{W.numpy()=}, {np.sum(X.numpy() * Z.numpy())=}")
```
Before the first failed assert prints:
```
W.numpy()=array(109.48644, dtype=float32), np.sum(X.numpy() * Z.numpy())=3.8519936e+17
W.numpy()=array(3.8519936e+17, dtype=float32), np.sum(X.numpy() * Z.numpy())=-9.629987e+34
/home/tcoard/w/fun/lin_alg/new.py:30: RuntimeWarning: overflow encountered in multiply
  assert np.allclose(W.numpy(), np.sum(X.numpy() * Z.numpy()))
```

System details:
numpy==1.22.2
loop-tool==0.1.0
CPU Architecture: x86_64

Let me know if there are any other details that would be helpful.

**Comment by bwasti** [comment]
Good catch, thanks for the heads up!

I've changed the README here: https://github.com/facebookresearch/loop_tool/commit/cbd7c4551b3b5ed83f0406cc5b0e43ce3d3ad977

The "set" API has some interesting edge cases introduced by newer features, so I removed that
use to fix the assertions.  However, this brings up the issue of unexpected behavior that'll need to be
fixed.

I've filed a new issue here: #7
